# Generated by Django 2.2.1 on 2019-05-06 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_balance', models.DecimalField(decimal_places=3, default=0, max_digits=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('wallet_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('VERIFICATION', 'VERIFICATION'), ('VIEWING', 'VIEWING')], max_length=20)),
                ('transaction_amount', models.DecimalField(decimal_places=3, default=0, max_digits=20)),
                ('date_transacted', models.DateTimeField(auto_now_add=True)),
                ('related_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_wallet', to='wallets.Wallet')),
            ],
        ),
    ]
