# Generated by Django 2.2.1 on 2019-05-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='wallet_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
