# Generated by Django 2.2.1 on 2019-05-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_wallet_wallet_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransactions',
            name='transaction_type',
            field=models.CharField(choices=[('TOP-UP', 'TOP-UP'), ('VERIFICATION', 'VERIFICATION'), ('VIEWING', 'VIEWING')], max_length=20),
        ),
    ]
