# Generated by Django 2.2.1 on 2019-05-06 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_auto_20190506_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
