# Generated by Django 2.2.1 on 2019-05-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_auto_20190506_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='wallet_private_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='wallet_public_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
