# Generated by Django 2.2.1 on 2019-05-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0005_auto_20190507_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='is_institution_wallet',
            field=models.BooleanField(default=False),
        ),
    ]
