# Generated by Django 2.2.1 on 2019-05-14 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0006_wallet_is_institution_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransactions',
            name='related_wallet',
        ),
        migrations.AddField(
            model_name='wallettransactions',
            name='input_wallet_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input_wallet_address', to='wallets.Wallet'),
        ),
        migrations.AddField(
            model_name='wallettransactions',
            name='output_wallet_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='output_wallet_address', to='wallets.Wallet'),
        ),
        migrations.AddField(
            model_name='wallettransactions',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
