# Generated by Django 2.2.1 on 2019-05-16 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0008_escrowtransactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayTokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_issued', models.CharField(max_length=400)),
                ('expected_token_cost', models.DecimalField(decimal_places=3, default=0, max_digits=20)),
                ('date_to_expire', models.DateTimeField(blank=True, null=True)),
                ('date_issued', models.DateTimeField(auto_now_add=True)),
                ('issued_to_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_issued_wallet_address', to='wallets.Wallet')),
                ('issuer_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_issuer_wallet_address', to='wallets.Wallet')),
            ],
        ),
    ]
