# Generated by Django 2.2.1 on 2019-05-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0009_paytokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='paytokens',
            name='token_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paytokens',
            name='transaction_id_generated',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
