# Generated by Django 2.2.1 on 2019-05-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0010_auto_20190516_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowtransactions',
            name='is_certificate_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='escrowtransactions',
            name='is_document_verification',
            field=models.BooleanField(default=False),
        ),
    ]
