# Generated by Django 2.2.1 on 2019-05-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0011_auto_20190516_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowtransactions',
            name='escrow_active',
            field=models.BooleanField(default=False),
        ),
    ]
