# Generated by Django 2.2.1 on 2019-05-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0012_escrowtransactions_escrow_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrowtransactions',
            name='escrow_active',
            field=models.BooleanField(default=True),
        ),
    ]
