# Generated by Django 2.2.1 on 2019-05-06 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=100)),
                ('certificate_link', models.ImageField(blank=True, null=True, upload_to='certificates')),
                ('institution_public_key', models.CharField(blank=True, max_length=300, null=True)),
                ('issued_on', models.DateTimeField(auto_now_add=True)),
                ('certificate_owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_owner_student', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_issuer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
