# Generated by Django 2.2.1 on 2019-05-06 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=100)),
                ('institution_public_key', models.CharField(blank=True, max_length=300, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='issued_by',
        ),
        migrations.AddField(
            model_name='certificate',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='certificate',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_issuer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_link',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_owner_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CertificateViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_viewed', models.DateTimeField(auto_now_add=True)),
                ('viewed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_viewer', to=settings.AUTH_USER_MODEL)),
                ('viewed_certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_viewed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
