# Generated by Django 2.2.1 on 2019-05-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_auto_20190506_0750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='issued_on',
            new_name='uploaded_on',
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='verified',
            new_name='verification_status',
        ),
        migrations.AddField(
            model_name='certificate',
            name='verified_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_link',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
