# Generated by Django 2.2.1 on 2019-05-06 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutions', '0005_certificateverificationrequests_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateverificationrequests',
            name='requested_by',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='requested_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
