# Generated by Django 2.2.1 on 2019-05-13 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutions', '0006_certificateverificationrequests_requested_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificateverificationrequests',
            name='certificate_id',
        ),
        migrations.RemoveField(
            model_name='certificateverificationrequests',
            name='institution_id',
        ),
        migrations.RemoveField(
            model_name='certificateverificationrequests',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='certificateviews',
            name='viewed_by',
        ),
        migrations.RemoveField(
            model_name='certificateviews',
            name='viewed_certificate',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='institution_public_key',
        ),
        migrations.AddField(
            model_name='institution',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institution_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='CertificateVerificationRequests',
        ),
        migrations.DeleteModel(
            name='CertificateViews',
        ),
    ]
