# Generated by Django 2.2.1 on 2019-05-27 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=200, null=True)),
                ('student_number', models.CharField(blank=True, max_length=200, null=True)),
                ('verification_status', models.BooleanField(default=False)),
                ('verified_on', models.DateTimeField(blank=True, null=True)),
                ('certificate_link', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('certificate_signature_link', models.FileField(blank=True, null=True, upload_to='certificates/signatures/')),
                ('institution_public_key', models.CharField(blank=True, max_length=300, null=True)),
                ('unique_string_nonce', models.CharField(blank=True, max_length=200, null=True)),
                ('certificate_unique_hash', models.CharField(blank=True, max_length=250, null=True)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('certificate_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_owner_wallet', to='wallets.Wallet')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_issuer', to='wallets.Wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_link', models.FileField(upload_to='documents/')),
                ('document_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_on', models.DateTimeField(blank=True, null=True)),
                ('document_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_owner_wallet', to='wallets.Wallet')),
            ],
        ),
        migrations.CreateModel(
            name='CertificateViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_viewed', models.DateTimeField(auto_now_add=True)),
                ('viewed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_viewer', to=settings.AUTH_USER_MODEL)),
                ('viewed_certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_viewed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CertificateViewRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_document_verification', models.BooleanField(default=False)),
                ('is_certificate_view', models.BooleanField(default=False)),
                ('verification_view_status', models.BooleanField(default=False)),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('certificate_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_to_be_viewed', to='certificates.Certificate')),
                ('document_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_to_be_verified', to='certificates.Documents')),
                ('escrow_transaction_related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escrow_transaction_related', to='wallets.EscrowTransactions')),
                ('requesting_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_requesting_verification', to='wallets.Wallet')),
                ('verifying_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_verifying_request', to='wallets.Wallet')),
            ],
        ),
        migrations.CreateModel(
            name='CertificateFeesSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_verification_fee', models.DecimalField(decimal_places=3, default=0, max_digits=20)),
                ('certificate_reverification_fee', models.DecimalField(decimal_places=3, default=0, max_digits=20)),
                ('certificate_view_access_fee', models.DecimalField(decimal_places=3, default=0, max_digits=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
