# Generated by Django 2.2.1 on 2019-05-13 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallets', '0005_auto_20190507_0805'),
        ('institutions', '0007_auto_20190513_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_link', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('document_signature_link', models.FileField(blank=True, null=True, upload_to='documents/signatures')),
                ('uploaded_on', models.DateTimeField(blank=True, null=True)),
                ('document_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_owner_wallet', to='wallets.Wallet')),
            ],
        ),
        migrations.CreateModel(
            name='CertificateViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_viewed', models.DateTimeField(auto_now_add=True)),
                ('viewed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_viewer', to=settings.AUTH_USER_MODEL)),
                ('viewed_certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_viewed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CertificateVerificationRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_status', models.BooleanField(default=False)),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_to_be_verified', to='certificates.Documents')),
                ('institution_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_to_verify', to='institutions.Institution')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_by', to='wallets.Wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_status', models.BooleanField(default=False)),
                ('verified_on', models.DateTimeField(blank=True, null=True)),
                ('certificate_link', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('certificate_signature_link', models.FileField(blank=True, null=True, upload_to='certificates/signatures/')),
                ('institution_public_key', models.CharField(blank=True, max_length=300, null=True)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('certificate_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_owner_wallet', to='wallets.Wallet')),
                ('institution_attached', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institution_attached', to='institutions.Institution')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_issuer', to='wallets.Wallet')),
            ],
        ),
    ]
