# Generated by Django 2.2.1 on 2019-05-16 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateFeesSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_verification_fee', models.DecimalField(decimal_places=3, default=0, max_digits=20)),
                ('certificate_reverification_fee', models.DecimalField(decimal_places=3, default=0, max_digits=20)),
                ('certificate_view_access_fee', models.DecimalField(decimal_places=3, default=0, max_digits=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
