# Generated by Django 2.2.1 on 2019-05-16 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0011_auto_20190516_0959'),
        ('certificates', '0002_certificatefeessettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateViewRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_document_verification', models.BooleanField(default=False)),
                ('is_certificate_view', models.BooleanField(default=False)),
                ('verification_view_status', models.BooleanField(default=False)),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('certificate_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_to_be_viewed', to='certificates.Certificate')),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_to_be_verified', to='certificates.Documents')),
                ('requesting_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_requesting_verification', to='wallets.Wallet')),
                ('verifying_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_verifying_request', to='wallets.Wallet')),
            ],
        ),
        migrations.DeleteModel(
            name='CertificateVerificationRequests',
        ),
    ]
