# Generated by Django 2.2.1 on 2019-05-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_auto_20190520_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='document_link',
            field=models.FileField(default=1, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
