# Generated by Django 2.2.1 on 2019-05-27 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0006_auto_20190527_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_unique_hash',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
