# Generated by Django 2.2.1 on 2019-05-27 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0007_certificate_certificate_unique_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='unique_string_nonce',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
