# Generated by Django 2.2.1 on 2019-05-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0008_certificate_unique_string_nonce'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='document_verified',
            field=models.BooleanField(default=False),
        ),
    ]
