# Generated by Django 2.2.1 on 2019-05-27 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0009_documents_document_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='document_verified',
        ),
    ]
