# Generated by Django 2.2.1 on 2019-05-27 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0012_escrowtransactions_escrow_active'),
        ('certificates', '0010_remove_documents_document_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateviewrequests',
            name='escrow_transaction_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escrow_transaction_related', to='wallets.EscrowTransactions'),
        ),
    ]
